sudo: required
dist: trusty

language: python
python:
  - 3.5

addons:
  apt:
    sources:
      - deadsnakes

before_install:
  - sudo apt-get update -q
  - make pkgs
  - make install

script:
  - make test

notifications:
  slack:
    rooms:
      - cs373-idb:CaojsymuHi3OqnMrrh92Owxa#builds
