sudo: required
dist: trusty

language: python
python:
  - 3.5

services:
  - postgresql

addons:
  apt:
    sources:
      - deadsnakes
  postgresql: "9.5"

before_install:
  - sudo apt-get update -q
  - make pkgs

before_script:
  - psql -c 'create database idb_test;' -U postgres
  - make db_migrations

script:
  - make test_all

notifications:
  slack:
    rooms:
      - cs373-idb:CaojsymuHi3OqnMrrh92Owxa#builds
