FORMAT: 1A
HOST: http://www.pokemans.me/api/v1/

# Pokemans

Pokemans is a simple API allowing clients to retrieve data on pokemon, pokedexes,
and moves.

# Group Pokemon

## Pokemon Collection [/pokemon?page={page}]
+ Parameters
    + page (number) - (optional, default: 1) the page number. 

### List All Pokemon [GET]

+ Response 200 (application/json)

        {
            "data": [
                {
                    "flavor_text": "Bulbasaur can be seen napping in bright sunlight.\nThere is a seed on its back. By soaking up the sun\u2019s rays,\nthe seed grows progressively larger",
                    "id": 1,
                    "habitat" : "grassland",
                    "color" : "green",
                    "shape" : "quadruped", 
                    "name" : "Bulbasaur"
                },
                {
                    "flavor_text": "The flame that burns at the tip of its tail is an indication\nof its emotions. The flame wavers when Charmander\nis enjoying itself. If the Pok\u00e9mon becomes enraged,\nthe flame burns fiercely.",
                    "id": 4,
                    "habitat" : "mountain",
                    "color" : "red",
                    "shape" : "upright", 
                    "name" : "Charmander"
                },
                {
                    "flavor_text": "Squirtle\u2019s shell is not merely used for protection.\nThe shell\u2019s rounded shape and the grooves on its\nsurface help minimize resistance in water,\nenabling this Pok\u00e9mon to swim at high speeds.",
                    "id": 7,
                    "habitat" : "waters-edge",
                    "color" : "blue",
                    "shape" : "upright", 
                    "name" : "Squirtle"
                }
            ],
            "has_next": true,
            "has_previous": false,
            "page": 1,
            "total_items": 9,
            "total_pages": 3
        }

### Add a Pokemon to the Database [POST]
+ Request (application/json)

        {
            "flavor_text": "Bulbasaur can be seen napping in bright sunlight.\nThere is a seed on its back. By soaking up the sun\u2019s rays,\nthe seed grows progressively larger",
            "id": 1,
            "habitat" : "grassland",
            "color" : "green",
            "shape" : "quadruped", 
            "name" : "Bulbasaur"
        }

+ Response 201 (application/json)

        {
          "data": {
            "flavor_text": "Bulbasaur can be seen napping in bright sunlight.\nThere is a seed on its back. By soaking up the sun\u2019s rays,\nthe seed grows progressively larger",
            "id": 1,
            "habitat" : "grassland",
            "color" : "green",
            "shape" : "quadruped", 
            "name" : "Bulbasaur",
            "pokedexes" : [1, 2, 7],
            "moves" : [33, 15]
          }
        }

+ Response 400

        {
            'errors': {
                'input': ['the server could not read the input as JSON']
            }
        }

+ Response 422

        {
            'errors': {
                'database': ['Unable to add pokemon to database']
            }
        }



## Pokemon [/pokemon/{pokemon_id}]
+ Parameters
    + pokemon_id (number) - the ID of a Pokemon

### Get all the attributes of a particular Pokemon. [GET]
+ Response 200 (application/json)

        {
          "data": {
            "flavor_text": "Bulbasaur can be seen napping in bright sunlight.\nThere is a seed on its back. By soaking up the sun\u2019s rays,\nthe seed grows progressively larger",
            "id": 1,
            "habitat" : "grassland",
            "color" : "green",
            "shape" : "quadruped", 
            "name" : "Bulbasaur",
            "pokedexes" : [1, 2, 7],
            "moves" : [33, 15]
          }
        }

+ Response 404 (application/json)

        {
            'errors': {
                'pokemon': ['pokemon with id does not exist']
            }
        }

### Update a Pokemon  [PUT]
+ Request (application/json)

        {
          "data": {
            "color" : "red"
          }
        }

+ Response 200 (application/json)

        {
          "data": {
            "flavor_text": "Bulbasaur can be seen napping in bright sunlight.\nThere is a seed on its back. By soaking up the sun\u2019s rays,\nthe seed grows progressively larger",
            "id": 1,
            "habitat" : "grassland",
            "color" : "red",
            "shape" : "quadruped", 
            "name" : "Bulbasaur",
            "pokedexes" : [1, 2, 7],
            "moves" : [33, 15]
          }
        }

+ Response 404 (application/json)

        {
            'errors': {
                'pokemon': ['pokemon with id does not exist']
            }
        }

+ Response 400 (application/json)

        {
            'errors': {
                'input': ['the server could not read the input as JSON']
            }
        }

+ Response 422 (application/json)

        {
            'errors': {
                'database': ['Unable to update pokemon in database']
            }
        }

### Delete a Pokemon [DELETE]
+ Response 200

        {
          "data": {
            "flavor_text": "Bulbasaur can be seen napping in bright sunlight.\nThere is a seed on its back. By soaking up the sun\u2019s rays,\nthe seed grows progressively larger",
            "id": 1,
            "habitat" : "grassland",
            "color" : "red",
            "shape" : "quadruped", 
            "name" : "Bulbasaur",
            "pokedexes" : [1, 2, 7],
            "moves" : [33, 15]
          }
        }

+ Response 404 (application/json)

        {
            'errors': {
                'pokemon': ['pokemon with id does not exist']
            }
        }

+ Response 422 (application/json)

        {
            'errors': {
                'database': ['Unable to update pokemon in database']
            }
        }


# Group Pokedexes

## Pokedex Collection [/pokedexes?page={page}]
+ Parameters
    + page (number) - (optional, default: 1) the page number. 

### List All Pokedexes [GET]

+ Response 200 (application/json)

        {
          "data": [
            {
              "description": "Entire National Dex",
              "id": 1,
              "name": "national",
              "official_name": "National",
              "region": null
            },
            {
              "description": "Red/Blue/Yellow Kanto dexDex",
              "id": 2,
              "name": "kanto",
              "official_name": "Kanto",
              "region": "kanto"
            },
            {
              "description": "HeartGold/SoulSilver Johto dex—Gold/Silver/Crystal's, extended to add move-based Generation IV evolutions",
              "id": 7,
              "name": "updated-johto",
              "official_name": "Updated Johto",
              "region": "johto"
            }
          ],
          "has_next": true,
          "has_previous": false,
          "page": 1,
          "total_items": 15,
          "total_pages": 5
        }

### Add a Pokedex to the Database [POST]
+ Request (application/json)

        {
          "data": {
            "description": "Entire National Dex",
            "id": 1,
            "name": "national",
            "official_name": "National",
            "pokemon": [1, 4, 7],
            "region": null
          }
        }

+ Response 201 (application/json)

        {
          "data": {
            "description": "Entire National Dex",
            "id": 1,
            "name": "national",
            "official_name": "National",
            "pokemon": [1, 4, 7],
            "region": null
          }
        }

+ Response 400

        {
            'errors': {
                'input': ['the server could not read the input as JSON']
            }
        }

+ Response 422

        {
            'errors': {
                'database': ['Unable to add pokedex to database']
            }
        }

## Pokedex [/pokedex/{pokedex_id}]
+ Parameters
    + pokedex_id (number) - the ID of a Pokedex

### Get all the attributes of a particular Pokedex. [GET]
+ Response 200 (application/json)

        {
          "data": {
            "description": "Entire National Dex",
            "id": 1,
            "name": "national",
            "official_name": "National",
            "pokemon": [1, 4, 7],
            "region": null
          }
        }

+ Response 404 (application/json)

        {
            'errors': {
                'pokedex': ['pokedex with id does not exist']
            }
        }

### Update a Pokedex  [PUT]
+ Request (application/json)

        {
          "data": {
            "region" : "kanto"
          }
        }

+ Response 200 (application/json)

        {
          "data": {
            "description": "Entire National Dex",
            "id": 1,
            "name": "national",
            "official_name": "National",
            "pokemon": [1, 4, 7],
            "region": "kanto"
          }
        }

+ Response 404 (application/json)

        {
            'errors': {
                'pokedex': ['pokedex with id does not exist']
            }
        }

+ Response 400 (application/json)

        {
            'errors': {
                'input': ['the server could not read the input as JSON']
            }
        }

+ Response 422 (application/json)

        {
            'errors': {
                'database': ['Unable to update pokedex in database']
            }
        }

### Delete a Pokedex [DELETE]
+ Response 200

        {
          "data": {
            "description": "Entire National Dex",
            "id": 1,
            "name": "national",
            "official_name": "National",
            "pokemon": [1, 4, 7],
            "region": null
          }
        }

+ Response 404 (application/json)

        {
            'errors': {
                'pokedex': ['pokedex with id does not exist']
            }
        }

+ Response 422 (application/json)

        {
            'errors': {
                'pokedex': ['Unable to update pokedex in database']
            }
        }


# Group Moves

## Moves Collection [/moves?page={page}]
+ Parameters
    + page (number) - (optional, default: 1) the page number. 

### List All Moves [GET]

+ Response 200 (application/json)

        {
          "data": [
            {
              "flavor_text": "A physical attack in which the user\ncharges and slams into the target\nwith its whole body.",
              "id": 33,
              "short_effect" : "Inflicts regular damage with no additional effect.",
              "effect" : "Inflicts regular damage.",
              "damage_class" : "physical",
              "power_points" : 35,
              "power" : 50,
              "accuracy" : 100, 
              "name" : "Tackle"
            },
            {
              "flavor_text": "Hard, pointed, sharp claws rake\nthe target to inflict damage.",
              "id": 10,
              "short_effect" : "Inflicts regular damage with no additional effect.",
              "effect" : "Inflicts regular damage.",
              "damage_class" : "physical",
              "power_points" : 35,
              "power" : 40,
              "accuracy" : 100, 
              "name" : "Scratch"
            },
            {
              "flavor_text": "The target is cut with a scythe or claw.\nThis can also be used to cut down thin trees.",
              "id": 15,
              "short_effect" : "Inflicts regular damage with no additional effect.",
              "effect" : "Inflicts regular damage.",
              "damage_class" : "physical",
              "power_points" : 30,
              "power" : 50,
              "accuracy" : 95, 
              "name" : "Cut"
            }
          ],
          "has_next": true,
          "has_previous": false,
          "page": 1,
          "total_items": 9,
          "total_pages": 3
        }

### Add a Move to the Database [POST]
+ Request (application/json)

        {
          "data": {
            "flavor_text": "Hard, pointed, sharp claws rake\nthe target to inflict damage.",
            "id": 10,
            "short_effect" : "Inflicts regular damage with no additional effect.",
            "effect" : "Inflicts regular damage.",
            "damage_class" : "physical",
            "power_points" : 35,
            "power" : 40,
            "accuracy" : 100, 
            "name" : "Scratch",
            "pokemon" : [4]
          }
        }


+ Response 201 (application/json)

        {
          "data": {
            "flavor_text": "Hard, pointed, sharp claws rake\nthe target to inflict damage.",
            "id": 10,
            "short_effect" : "Inflicts regular damage with no additional effect.",
            "effect" : "Inflicts regular damage.",
            "damage_class" : "physical",
            "power_points" : 35,
            "power" : 40,
            "accuracy" : 100, 
            "name" : "Scratch",
            "pokemon" : [4]
          }
        }


+ Response 400

        {
            'errors': {
                'input': ['the server could not read the input as JSON']
            }
        }

+ Response 422

        {
            'errors': {
                'database': ['Unable to add move to database']
            }
        }

## Move [/moves/{move_id}]
+ Parameters
    + move_id (number) - the ID of a move

### Get all the attributes of a particular Move. [GET]
+ Response 200 (application/json)

        {
          "data": {
            "flavor_text": "Hard, pointed, sharp claws rake\nthe target to inflict damage.",
            "id": 10,
            "short_effect" : "Inflicts regular damage with no additional effect.",
            "effect" : "Inflicts regular damage.",
            "damage_class" : "physical",
            "power_points" : 35,
            "power" : 40,
            "accuracy" : 100, 
            "name" : "Scratch",
            "pokemon" : [4]
          }
        }

+ Response 404 (application/json)

        {
            'errors': {
                'move': ['move with id does not exist']
            }
        }

### Update a Move  [PUT]
+ Request (application/json)

        {
          "data": {
            "name" : "Fire Blast"
          }
        }

+ Response 200 (application/json)

        {
          "data": {
            "flavor_text": "Hard, pointed, sharp claws rake\nthe target to inflict damage.",
            "id": 10,
            "short_effect" : "Inflicts regular damage with no additional effect.",
            "effect" : "Inflicts regular damage.",
            "damage_class" : "physical",
            "power_points" : 35,
            "power" : 40,
            "accuracy" : 100, 
            "name" : "Fire Blast",
            "pokemon" : [4]
          }
        }


+ Response 404 (application/json)

        {
            'errors': {
                'move': ['move with id does not exist']
            }
        }

+ Response 400 (application/json)

        {
            'errors': {
                'input': ['the server could not read the input as JSON']
            }
        }

+ Response 422 (application/json)

        {
            'errors': {
                'database': ['Unable to update move in database']
            }
        }

### Delete a Move [DELETE]
+ Response 200

        {
          "data": {
            "flavor_text": "Hard, pointed, sharp claws rake\nthe target to inflict damage.",
            "id": 10,
            "short_effect" : "Inflicts regular damage with no additional effect.",
            "effect" : "Inflicts regular damage.",
            "damage_class" : "physical",
            "power_points" : 35,
            "power" : 40,
            "accuracy" : 100, 
            "name" : "Scratch",
            "pokemon" : [4]
          }
        }


+ Response 404 (application/json)

        {
            'errors': {
                'move': ['move with id does not exist']
            }
        }

+ Response 422 (application/json)

        {
            'errors': {
                'move': ['Unable to update move in database']
            }
        }

# Group Associations

## Pokemon and Pokedex [/pokedex_pokemon/]

### Associate a Pokemon with a Pokedex [POST]
+ Request (application/json)

        {
          "data": {
            "pokemon_id" : 1,
            "pokedex_id" : 8
          }
        }

+ Response 200

        {
          "data": {
            "success" : True
          }
        }

+ Response 404 (application/json)

        {
            'errors': {
                'pokemon': ['pokemon with id does not exist']
            }
        }

+ Response 400 (application/json)

        {
            'errors': {
                'input': ['the server could not read the input as JSON']
            }
        }

+ Response 422 (application/json)

        {
            'errors': {
                'database': ['Unable to associate pokedex and pokemon']
            }
        }

## Pokemon and Move [/pokemon_moves/]

### Associate a Pokemon with a Move [POST]
+ Request (application/json)

        {
          "data": {
            "pokemon_id" : 1,
            "move_id" : 75
          }
        }

+ Response 200

        {
          "data": {
            "success" : True
          }
        }

+ Response 404 (application/json)

        {
            'errors': {
                'pokemon': ['pokemon with id does not exist']
            }
        }

+ Response 400 (application/json)

        {
            'errors': {
                'input': ['the server could not read the input as JSON']
            }
        }

+ Response 422 (application/json)

        {
            'errors': {
                'database': ['Unable to associate pokemon and move']
            }
        }